### ISSUE TITLE
Migration to version 14.0

### ISSUE THREAD

**Issue by oihane** [avanzosc/odoo-addons#1050]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0

# Modules to migrate

- [ ] account_analytic_billing_plan
- [ ] account_analytic_line_with_project
- [ ] account_bank_multiple_partner
- [ ] account_banking_mandate_usability
- [ ] account_invoice_company_bank_currency
- [ ] account_invoice_fiscal_position_text
- [ ] account_invoice_line_lot
- [ ] account_invoice_lines_recalculate
- [ ] account_invoice_report_utilities
- [ ] account_invoice_usability
- [ ] account_invoice_validate_vendor_line
- [ ] analytic_usability
- [ ] base_month
- [ ] calendar_school
- [ ] calendar_survey
- [ ] contacts_school
- [ ] contacts_school_permission
- [ ] contract_line_menu
- [ ] contract_sale_school
- [ ] contract_school
- [ ] contract_template_print_section
- [ ] education_group_mail_list
- [ ] email_template_without_link
- [ ] fleet_route
- [ ] fleet_route_contract
- [ ] fleet_route_reports
- [ ] fleet_route_school
- [ ] fleet_route_support
- [ ] invoice_customer_ref
- [ ] ir_attachment_download
- [ ] partner_equal_ref_barcode
- [ ] partner_group
- [ ] partner_language_skill
- [ ] product_attribute_type
- [ ] product_attribute_value_image
- [ ] product_availability_report
- [ ] product_pricelist_item_menu
- [ ] product_recurring
- [ ] product_sequence_by_category
- [ ] product_supplierinfo_purchase_price
- [ ] product_template_attribute_value_menu
- [ ] product_usability
- [ ] product_utilities
- [ ] purchase_line_copy_purchase_input
- [ ] purchase_order_date_ready_forwarded
- [ ] purchase_order_line_copy
- [ ] purchase_order_line_description_from_sale
- [ ] purchase_order_line_input
- [ ] purchase_partner_company
- [ ] purchase_stock_picking_analytic
- [ ] res_partner_student_fields
- [ ] resource_bonus
- [ ] resource_rest_time
- [ ] resource_time
- [ ] sale_invoice_lines_history
- [ ] sale_order_line_inventory
- [ ] sale_order_optional_products_addition
- [ ] sale_stock_picking_analytic
- [ ] server_action_security
- [ ] stock_forecast
- [ ] stock_move_purchase_unit_price
- [ ] stock_move_sale_unit_price
- [ ] stock_move_with_partner
- [ ] stock_picking_analytic
- [ ] stock_picking_complementary
- [ ] stock_picking_lots
- [ ] stock_picking_move_excess_material
- [ ] stock_picking_ordered
- [ ] stock_picking_ordered_batch_extended
- [ ] stock_picking_sorted
- [ ] stock_picking_template
- [ ] stock_production_lot_with_partner
- [ ] stock_run_scheduler_manually
- [ ] stock_usability
- [ ] survey_usability
- [ ] website_base_filter
- [ ] website_catalog
- [ ] website_crm_claim
- [ ] website_crm_lead
- [ ] website_edit_button_delete
- [ ] website_invoice_filter
- [ ] website_sale_filter
- [ ] website_stock

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list
