### ISSUE TITLE
Migration to version 15.0

### ISSUE THREAD

**Issue by oihane** [avanzosc/odoo-addons#1578]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0

# Modules to migrate

- [ ] account_analytic_campaign
- [ ] account_bank_multiple_partner
- [ ] account_banking_mandate_usability
- [ ] account_headquarter
- [ ] account_invoice_event_report
- [ ] account_invoice_report_grouped_by_event
- [ ] account_invoice_report_show_payment_reference
- [ ] account_invoice_with_event_ticket
- [ ] account_invoice_with_start_end_date_period
- [ ] account_move_time_type
- [ ] analytic_usability
- [ ] calendar_event_description
- [ ] calendar_event_resource
- [ ] calendar_timesheet
- [ ] contact_employment_info
- [ ] contract_line_menu
- [ ] custom_breeding
- [ ] custom_saca
- [ ] education_center
- [ ] education_center_account
- [ ] event_additional_material
- [ ] event_attendee_birthdate
- [ ] event_commute
- [ ] event_create_track
- [ ] event_event_resource
- [ ] event_extended_name
- [ ] event_headquarter
- [ ] event_lang_level
- [ ] event_name_code_year_id
- [ ] event_no_copy_stage
- [ ] event_price_shared
- [ ] event_price_shared_fix
- [ ] event_registration_action
- [ ] event_registration_autocomplete
- [ ] event_registration_autocomplete_birthdate
- [ ] event_registration_confirm_group
- [ ] event_registration_contact_type
- [ ] event_registration_create_student
- [ ] event_registration_generate_email
- [ ] event_registration_member
- [ ] event_registration_sale
- [ ] event_registration_sale_line_contract
- [ ] event_registration_signup_url
- [ ] event_registration_student
- [ ] event_responsible_force_employee
- [ ] event_responsible_force_employee_lang_level
- [ ] event_sale_registration_action
- [ ] event_schedule
- [ ] event_slides
- [ ] event_student_history
- [ ] event_track_analytic
- [ ] event_track_analytic_second_responsible
- [ ] event_track_calendar_report
- [ ] event_track_cancel_billability
- [ ] event_track_cancel_reason
- [ ] event_track_participant
- [ ] event_track_replanification
- [ ] event_track_usability
- [ ] event_training_itinerary
- [ ] event_zoom_link
- [ ] external_layout_standard_logo_size
- [ ] fleet_extension
- [ ] partner_academic_background
- [ ] partner_commercial_by_language
- [ ] partner_contact_birthdate_visibility
- [ ] partner_contact_type
- [ ] partner_contact_type_analytic_account
- [ ] partner_medical_record_number
- [ ] partner_rsipac
- [ ] partner_skills
- [ ] partner_zone
- [ ] portal_wizard_extension
- [ ] product_editable_tree_menu
- [ ] product_material
- [ ] product_plane_number
- [ ] product_second_uom
- [ ] product_state_tag
- [ ] product_storable_generate_task
- [ ] product_storable_generate_task_estimated_hours
- [ ] product_template_lineal
- [ ] product_template_variant_create
- [ ] product_template_year_consumption
- [ ] product_usability
- [ ] product_vat_price
- [ ] product_vehicle_model
- [ ] purchase_contact_partner
- [ ] purchase_order_headquarter
- [ ] purchase_order_shipping_method
- [ ] quality_control_private_test
- [ ] recruitment_date
- [ ] res_country_state_usability
- [ ] res_partner_extra_email
- [ ] res_partner_headquarter
- [ ] res_partner_reference_usability
- [ ] resource_time
- [ ] slide_channel_attachment
- [ ] slide_channel_event_responsible
- [ ] slide_channel_phase
- [ ] slide_channel_survey
- [ ] slide_channel_technology
- [ ] slide_partner_menu
- [ ] stock_dropshipping_customer_picking
- [ ] stock_location_warehouse_usability
- [ ] stock_move_availability
- [ ] stock_move_line_divide
- [ ] stock_move_line_force_done
- [ ] stock_move_line_package_dimension
- [ ] stock_orderpoint_generation
- [ ] stock_picking_analytic
- [ ] stock_picking_batch_breeding
- [ ] stock_picking_batch_farmer
- [ ] stock_picking_batch_mother
- [ ] stock_picking_batch_package
- [ ] stock_picking_date_done
- [ ] stock_picking_package_usability
- [ ] stock_picking_type_usability
- [ ] stock_production_lot_fleet_vehicle
- [ ] stock_production_lot_responsible
- [ ] stock_production_lot_state
- [ ] stock_warehouse_farm
- [ ] thermoformed_cost_calculation
- [ ] vehicle_license_plate_unique
- [ ] website_bank_account
- [ ] website_bootstrap_select
- [ ] website_event_member
- [ ] website_event_sale_confirm
- [ ] website_event_slides
- [ ] website_event_track_claim
- [ ] website_event_track_claim_multiple_advice
- [ ] website_event_track_zoom_link
- [ ] website_event_type_custom
- [ ] website_event_visibility
- [ ] website_login_custom
- [ ] website_payment_method_custom
- [ ] website_portal_custom
- [ ] website_portal_event_learning
- [ ] website_product_pricelist
- [ ] website_sale_multiple_coupon
- [ ] website_sale_zip_autocomplete

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list
