### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by oihane** [avanzosc/odoo-addons#535]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] OCA_descriptions
- [ ] account_analytic_analysis_recurring_day
- [ ] account_analytic_invoice_line_menu
- [ ] account_analytic_mass_close
- [ ] account_analytic_payment
- [ ] account_analytic_security
- [ ] account_banking_payment_transfer_mode
- [ ] account_invoice_attachment_download
- [ ] account_invoice_filter
- [ ] account_invoice_line_lot
- [ ] account_invoice_manual_analytic
- [ ] account_invoice_merge_massive
- [ ] account_invoice_merge_stock_picking
- [ ] account_invoice_partner_bank
- [ ] account_invoice_report_by_commercial
- [ ] account_invoice_supplier_ref_unique_by_fiscalyear
- [ ] account_invoice_supplier_validation
- [ ] account_invoice_temporal
- [ ] account_move_import
- [ ] account_partner_payment_report
- [ ] account_renumber_options
- [ ] account_utilities
- [ ] avanzosc_custom_reports
- [ ] avanzosc_sale_order_line_add_website
- [ ] avanzosc_theme
- [ ] base_module_utilities
- [ ] base_report_to_printer_configurator
- [ ] base_user_signature_logo
- [ ] calendar_event_without_group
- [ ] email_template_cron
- [ ] event_project_follower
- [x] event_report By @gotzonavanzosc  #614 
- [ ] invoice_duplicate_with_order
- [ ] localizable_project
- [ ] mail_document
- [ ] maintenance_contract
- [ ] mrp_label_print
- [ ] mrp_operations_extension_label_print
- [ ] partner_contact_birthdate_age
- [ ] partner_event_follower
- [ ] partner_parent_change
- [ ] partner_pickings
- [ ] partner_risk_configuration
- [ ] partner_student_course
- [x] partner_zone By @hprasetyou #575 
- [ ] payment_line_menu
- [ ] pos_discount_extra
- [ ] procurement_purchase_by_sale_contract
- [ ] procurement_service_project
- [ ] product_attribute_code_field
- [ ] product_deactivate_from_picking
- [ ] product_lot_reference_on_transfer
- [ ] product_product_calculated_dimensions
- [ ] product_sequence_by_category
- [ ] product_stock_on_hand
- [ ] product_supplierinfo_expand_view
- [ ] product_supplierinfo_import
- [ ] product_supplierinfo_view
- [ ] product_supplierinfo_view_variant
- [ ] product_training_plan
- [ ] product_upgrade_sale_cost_price
- [ ] product_variant_description
- [ ] product_variant_extra_price
- [ ] purchase_line_with_delivery_service_info
- [ ] purchase_order_line_view
- [ ] purchase_order_line_with_sale_account
- [ ] purchase_order_search_extended
- [ ] purchase_order_split
- [ ] purchase_requisition_back2draft
- [ ] purchase_requisition_from_sale_order
- [ ] purchase_requisition_purchase_price
- [ ] purchase_requisition_sale_price
- [ ] purchase_with_invoice_last_price
- [ ] report_odoo_logo
- [ ] res_partner_analytic
- [ ] res_partner_show_only_name
- [ ] sale_order_training_plan
- [ ] stock_account_payment_term
- [ ] stock_information
- [ ] stock_information_mrp
- [ ] stock_information_mrp_procurement_plan
- [ ] stock_information_sale_forecast
- [ ] stock_inventory
- [ ] stock_inventory_line_ext
- [ ] stock_inventory_negative_quants
- [ ] stock_label_print
- [ ] stock_lot_invoicing
- [ ] stock_lot_lifespan
- [ ] stock_move_automatic_assign
- [ ] stock_move_capture
- [ ] stock_move_generate_initial
- [ ] stock_orderpoint_filter
- [ ] stock_orderpoint_rule
- [ ] stock_picking_label_print
- [ ] stock_picking_service_sale
- [ ] stock_picking_transfer_limit
- [ ] stock_picking_valued_editable
- [ ] stock_planning_with_product_type
- [ ] stock_quant_expiry
- [ ] stock_quant_partner_info
- [ ] stock_quant_relocate
- [ ] stock_transfer_cancel
- [ ] stock_utilities
- [ ] stock_visible_cost
- [ ] warning_by_workflow
- [ ] website_cookielaw
- [ ] website_product_training_plan
- [ ] website_project_task
- [ ] website_quote_not_unlink
- [x] _website_sale_ext_ By @Daniel-CA - #597
