### ISSUE TITLE
Migration to version 12.0

### ISSUE THREAD

**Issue by oihane** [avanzosc/odoo-addons#688]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0

# Modules to migrate

- [ ] account_analytic_billing_plan
- [ ] account_analytic_line_product_root_category
- [ ] account_asset_utilities
- [ ] account_budget_distribution
- [ ] account_budget_expense
- [ ] account_budget_template
- [ ] account_utilities
- [ ] analytic_line_kind
- [ ] analytic_utilities
- [ ] base_characterization
- [ ] contract_specification
- [ ] event_characterization
- [ ] event_report
- [ ] l10n_eu_nace
- [ ] mail_template_characterization
- [ ] maintenance_equipment_analytic
- [ ] maintenance_equipment_extra_info
- [ ] maintenance_equipment_extra_info_asset
- [ ] mass_mailing_characterization
- [ ] partner_characterization
- [ ] partner_documentation
- [ ] partner_funding_source
- [ ] partner_group
- [ ] partner_opening_hours
- [ ] partner_social_media
- [ ] partner_success_story
- [ ] partner_zone
- [ ] product_customer_pricelist
- [ ] purchase_contract_specification
- [ ] stock_picking_with_analytic_account
- [ ] stock_utilities
- [ ] website_blog_characterization
- [ ] website_sale_ext
