### ISSUE TITLE
Migration to version 13.0

### ISSUE THREAD

**Issue by oihane** [avanzosc/odoo-addons#892]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0

# Modules to migrate

- [ ] account_analytic_billing_plan
- [ ] account_banking_mandate_usability
- [ ] account_invoice_company_bank_currency
- [ ] account_invoice_line_lot
- [ ] account_invoice_report_utilities
- [ ] account_invoice_usability
- [ ] analytic_usability
- [ ] base_month
- [ ] calendar_school
- [ ] calendar_survey
- [ ] contacts_school
- [ ] contacts_school_permission
- [ ] contract_sale_school
- [ ] contract_school
- [ ] education_group_mail_list
- [ ] fleet_route
- [ ] fleet_route_school
- [ ] fleet_route_support
- [ ] invoice_customer_ref
- [ ] ir_attachment_download
- [ ] partner_group
- [ ] partner_language_skill
- [ ] product_attribute_type
- [ ] product_availability_report
- [ ] product_pricelist_item_menu
- [ ] product_recurring
- [ ] product_sequence_by_category
- [ ] product_supplierinfo_purchase_price
- [ ] product_usability
- [ ] product_utilities
- [ ] purchase_order_date_ready_forwarded
- [ ] purchase_order_line_input
- [ ] purchase_partner_company
- [ ] purchase_stock_picking_analytic
- [ ] res_partner_student_fields
- [ ] resource_bonus
- [ ] resource_rest_time
- [ ] resource_time
- [ ] sale_invoice_lines_history
- [ ] sale_partner_company
- [ ] sale_stock_picking_analytic
- [ ] stock_forecast
- [ ] stock_picking_analytic
- [ ] stock_picking_lots
- [ ] stock_picking_template
- [ ] stock_run_scheduler_manually
- [ ] stock_usability
- [ ] survey_usability
- [ ] website_base_filter
- [ ] website_invoice_filter
- [ ] website_sale_filter

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list
